### ISSUE TITLE
File not found, could you help me?

### ISSUE THREAD

**Issue by TheonFNFModder** [Corne2Plum3/fnf2osumania#17] opened 2022-01-05 15:09 UTC
When I was porting Triple Trouble (4k Version) to osu!mania, an error appeared.

Traceback (most recent call last) :
   File "fnf_converter.py", line 529, in exportAsOsz
   File "site-packages\pydub\audio_segment.py", line 685, in from_file
   File "site-packages\pydub\utils.py", line 274, in mediainfo_json
   File "subprocess.py", line 800, in __init__
   File "subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 2] Не удается найти указанный файл

I used 1.1.4.

Windows 7 (Yes I know, I'm using a potato pc for osu and fnf, it still works tho.)

I used the .exe file, Idk if I used Python or not, but I think I have it installed.

**Additional context:**
So, I need to fix this bug ASAP, I'm working on a new beatmap pack and I shall finish it in 6 days.

**Comment by Corne2Plum3** [comment] 2022-01-05 23:13
Duplicate of #6, please check this.

**Closed by Corne2Plum3** 2022-01-05 23:13 UTC
Labels: bug
