### ISSUE TITLE
Unable to export

### ISSUE THREAD

**Issue by DJPopsicle** [Corne2Plum3/fnf2osumania#11] opened 2021-10-31 11:56 UTC
tried to export, got this.

Traceback (most recent call last):
  File "fnf_converter.py", line 529, in exportAsOsz
  File "site-packages\pydub\audio_segment.py", line 685, in from_file
  File "site-packages\pydub\utils.py", line 274, in mediainfo_json
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Corne2Plum3** [comment] 2021-10-31 12:10
Duplicate of #6 .

You don't have ffmpeg installed on your computer. You have to install it (I put a link to a YouTube tutorial on the READ.ME.md)

**Closed by Corne2Plum3** 2021-10-31 12:10 UTC
