### ISSUE TITLE
weird bug

### ISSUE THREAD

**Issue by Forecatfromthecatcrew** [Corne2Plum3/fnf2osumania#21] opened 2022-02-10 03:19 UTC
**Describe the bug**
pressed export error i got is below

**Error message**
Traceback (most recent call last):
  File "fnf_converter.py", line 529, in exportAsOsz
  File "site-packages\pydub\audio_segment.py", line 685, in from_file
  File "site-packages\pydub\utils.py", line 274, in mediainfo_json
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Screenshots:**
none

**Program version:**
1.1.2

**Plateform:**
Windows 10

**Comment by Corne2Plum3** [comment] 2022-02-10 05:43
Duplicate of #6

**Closed by Corne2Plum3** 2022-02-10 05:43 UTC
Labels: bug
