### ISSUE TITLE
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

### ISSUE THREAD

**Issue by nbn7272** [Corne2Plum3/fnf2osumania#14] opened 2021-11-29 19:11 UTC
**Describe the bug**
Describe what happened.
i cant convert

**Error message**
If you got an error message, post it here.
Traceback (most recent call last):
  File "fnf_converter.py", line 529, in exportAsOsz
  File "site-packages\pydub\audio_segment.py", line 685, in from_file
  File "site-packages\pydub\utils.py", line 274, in mediainfo_json
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

**Screenshots:**
![image](https://user-images.githubusercontent.com/90216658/143928036-b248dd95-72e8-4729-8115-6b755a7dae80.png)

**Program version:**
Which version of the program did you used when you encountered this bug? *(example: 1.0, 1.1.2, ...)*
1.1.4

**Plateform:**
What OS did you used? *(Windows 7/8/10, Linux, ...)*
windows 10

Also, please specify what did you used exactly *(the .exe file or the source code?)*. If you used Python, please specify the version of your Python *(example: Python 3.7.6)*
python 3.9

**Used files:**
If you input files in this program, post them here (just drag the files in this box), it would be useful to understand how the bug happened.
correct

**Additional context:**
Something to add?

**Comment by Corne2Plum3** [comment] 2021-11-30 06:43
Duplicate of #6

**Closed by Corne2Plum3** 2021-11-30 06:43 UTC
Labels: duplicate, missing requirements
