### ISSUE TITLE
Error while converting

### ISSUE THREAD

**Issue by Jadix120** [Corne2Plum3/fnf2osumania#15] opened 2021-12-21 21:15 UTC
**Describe the bug**
When i try to convert a song, i get this error everytime. I have ffmpeg installed and python 3.7.0

**Error message**
Traceback (most recent call last):
  File "fnf_converter.py", line 513, in exportAsOsz
  File "site-packages\pydub\audio_segment.py", line 685, in from_file
  File "site-packages\pydub\utils.py", line 274, in mediainfo_json
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Screenshots:**

**Program version:**
Which version of the program did you used when you encountered this bug? *(example: 1.0, 1.1.2, ...)*
1.1.3

**Plateform:**
What OS did you used? *(Windows 7/8/10, Linux, ...)*
Windows 10

Also, please specify what did you used exactly *(the .exe file or the source code?)*. If you used Python, please specify the version of your Python *(example: Python 3.7.6)*
I used the exe

**Comment by Corne2Plum3** [comment] 2021-12-21 23:35
Another duplicate of #6 .

**Closed by Corne2Plum3** 2021-12-21 23:35 UTC
Labels: duplicate, missing requirements
