### ISSUE TITLE
How do you fix this?

### ISSUE THREAD

**Issue by Godnoob443** [Corne2Plum3/fnf2osumania#1] opened 2021-10-01 20:32 UTC
Each time i try to export it i get this

Traceback (most recent call last):
  File "fnf_converter.py", line 505, in exportAsOsz
  File "site-packages\pydub\audio_segment.py", line 685, in from_file
  File "site-packages\pydub\utils.py", line 274, in mediainfo_json
  File "subprocess.py", line 753, in __init__
  File "subprocess.py", line 1054, in _get_handles
OSError: [WinError 6] The handle is invalid

**Comment by Corne2Plum3** [comment] 2021-10-02 11:15
1. Why you closed this issue? Did you fixed the bug?
2. If not, can you tell us what version of the program did you used and what OS did you used?

**Comment by Corne2Plum3** [comment] 2021-10-03 09:29
You're not the only with this error.

Probably a duplicate of #3, which provide more details. That why I close this issue now.

**Closed by Corne2Plum3** 2021-10-03 09:29 UTC
Labels: bug, missing details
